import mongoose from "mongoose";


const projectSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
        trim:true,
        maxlength:140
    },
    slug:{
        type:String,
        trim:true,
        index:true
    },
    subtitle:{
        type:String,
        required:true,
        trim:true,
        maxlength:220
    },
    techStuck:[
        {
            type:String,
            required:true,
            trim:true,
            maxlength:60
        }
    ],
    description:{
        type:String,
        required:true,
        trim:true,
        maxlength:10000
    },
    fetures:{
        type:String,
        required:true,
        trim:true,
        maxlength:8000
    },
    category:{
        type:String,
        required:true,
        trim:true,
        maxlength:80
    },
    client:{
        type:String,
        trim:true,
        maxlength:120,
        default:'Personal'
    },
    githubUrl:{
        type:String,
        trim:true,
        maxlength:1000
    },
    challenges:{
        type:String,
        trim:true,
        maxlength:8000
    },
    duration:{
        type:String,
        required:true,
        trim:true,
        maxlength:80
    },
    coverImage:{
        type:String,
        required:true,
        trim:true,
        maxlength:1000
    },
    screenshots:[
        {
            type:String,
            required:true,
            trim:true,
            maxlength:1000
        }
    ],
    projectUrl:{
        type:String,
        required:true,
        trim:true,
        maxlength:1000
    }
},{timestamps:true})

const Project=mongoose.model('Project',projectSchema);
export default Project;
